stages:
  - build

.build: &build_template
  stage: build
  variables:
    # see https://forum.gitlab.com/t/solved-preserve-file-permissions-on-git-clone/2460
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: 1
    GIT_STRATEGY: clone
  image:
    # The kaniko debug image is recommended (gcr.io/kaniko-project/executor:debug) because it has a shell, and a shell is required for an image to be used with GitLab CI/CD.
    name: gcr.io/kaniko-project/executor:debug
    # The entrypoint needs to be overridden, otherwise the build script doesn't run.
    entrypoint: [ "" ]
  script:
    # A Docker config.json file needs to be created with the authentication information for the desired container registry.
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
      else
        tag=":$CI_COMMIT_REF_SLUG"
      fi
    - /kaniko/executor 
      --context $CI_PROJECT_DIR/$DOCKER_CONTEXT 
      --dockerfile $CI_PROJECT_DIR/$DOCKERFILE_PATH 
      --destination "$CI_REGISTRY_IMAGE/$IMAGE_NAME${tag}"
      --cache-repo=$CI_REGISTRY_IMAGE/$IMAGENAME-cache
      --cache=true 
      --cache-copy-layers=true 
      --cache-ttl=96h
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - changes:
      - $DOCKER_CONTEXT/**/**
    - changes:
      - .gitlab-ci.yml
      when: manual
  timeout: 3h

build-project-multimodal-machine-learning-lab-wise24:
  extends: .build
  variables:
    DOCKERFILE_PATH: ./Dockerfile
    DOCKER_CONTEXT: .
    IMAGE_NAME: project-multimodal-machine-learning-lab-wise24
  when: manual
