defaults:
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

num_recommendations : 5
port: 2020
reconnect_timeout: 3
score_mode: emoji
device: cuda
image_display_size : [256, 256]
random_seed : 42

generator:
  num_inference_steps : 30
  guidance_scale: 7.5
  random_latents : False
  use_negative_prompt : False

recommender:
  extend_original_prompt : True
  n_embedding_axis : 13
  embedding_bounds : [0., 1.]
  use_embedding_center : True
  n_latent_axis : 3
  latent_bounds : [-1., 1.]
  use_latent_center : False

user_profile_host:
  beta: 20

path:
  output_dir: ./output/
  cache_dir: ./cache/
  images_save_dir: ./saved_images/
