defaults:
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

num_recommendations : 8
port: 8080
reconnect_timeout: 30
score_mode: emoji
device: cuda
image_display_size : [256, 256]
random_seed : 42
generator_warm_start: True

generator:
  num_inference_steps : 50
  guidance_scale: 7.5
  random_latents : False
  use_negative_prompt : False

recommender:
  extend_original_prompt : True
  n_embedding_axis : 13
  use_embedding_center : False
  n_latent_axis : 13
  use_latent_center : False
  ema_alpha : 0.5
  beta: 0.1
  beta_step_size: 0.1

path:
  output_dir: ./output/
  cache_dir: ./cache/
  images_save_dir: ./saved_images/
