defaults:
  - _self_

port: 8080

random_seed: 42

num_recommendations: 5

path:
  output_dir: ./output/
  cache_dir: ./cache/
  images_save_dir: ./saved_images/

hydra:
  run:
    dir: ${path.output_dir}
